[2021-11-17 23:20:04,929] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: mwaa-sm-customer-churn-dag.train manual__2021-11-18T07:18:46.123536+00:00 [queued]>
[2021-11-17 23:20:04,937] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: mwaa-sm-customer-churn-dag.train manual__2021-11-18T07:18:46.123536+00:00 [queued]>
[2021-11-17 23:20:04,937] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-17 23:20:04,938] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-17 23:20:04,938] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-17 23:20:04,950] {taskinstance.py:1262} INFO - Executing <Task(SageMakerTrainingOperator): train> on 2021-11-18 07:18:46.123536+00:00
[2021-11-17 23:20:04,954] {standard_task_runner.py:52} INFO - Started process 15669 to run task
[2021-11-17 23:20:04,962] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'mwaa-sm-customer-churn-dag', 'train', 'manual__2021-11-18T07:18:46.123536+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/mwaa-customer-churn-dag.py', '--cfg-path', '/var/folders/m8/kcmtvg3x5639v8tv9jcxd6700000gn/T/tmp49sk7kp7', '--error-file', '/var/folders/m8/kcmtvg3x5639v8tv9jcxd6700000gn/T/tmpp729s1qq']
[2021-11-17 23:20:04,964] {standard_task_runner.py:77} INFO - Job 35: Subtask train
[2021-11-17 23:20:05,010] {logging_mixin.py:109} INFO - Running <TaskInstance: mwaa-sm-customer-churn-dag.train manual__2021-11-18T07:18:46.123536+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-11-17 23:20:05,062] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=mwaa-sm-customer-churn-dag
AIRFLOW_CTX_TASK_ID=train
AIRFLOW_CTX_EXECUTION_DATE=2021-11-18T07:18:46.123536+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-18T07:18:46.123536+00:00
[2021-11-17 23:20:05,063] {sagemaker_base.py:89} INFO - Preprocessing the config and doing required s3_operations
[2021-11-17 23:20:05,064] {sagemaker_base.py:95} INFO - After preprocessing the config is:
 {
    "AlgorithmSpecification": {
        "TrainingImage": "433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:1",
        "TrainingInputMode": "File"
    },
    "HyperParameters": {
        "eta": "0.2",
        "gamma": "4",
        "max_depth": "5",
        "min_child_weight": "6",
        "num_round": "100",
        "objective": "binary:logistic",
        "subsample": "0.8"
    },
    "InputDataConfig": [
        {
            "ChannelName": "train",
            "ContentType": "text/csv",
            "DataSource": {
                "S3DataSource": {
                    "S3DataDistributionType": "FullyReplicated",
                    "S3DataType": "S3Prefix",
                    "S3Uri": "s3://shimingr-data/processed/train/"
                }
            }
        },
        {
            "ChannelName": "validation",
            "ContentType": "text/csv",
            "DataSource": {
                "S3DataSource": {
                    "S3DataDistributionType": "FullyReplicated",
                    "S3DataType": "S3Prefix",
                    "S3Uri": "s3://shimingr-data/processed/validation/"
                }
            }
        }
    ],
    "OutputDataConfig": {
        "S3OutputPath": "s3://shimingr-data/model/"
    },
    "ResourceConfig": {
        "InstanceCount": 1,
        "InstanceType": "ml.m5.4xlarge",
        "VolumeSizeInGB": 5
    },
    "RoleArn": "arn:aws:iam::846634201516:role/AmazonMWAA-SageMaker-Role",
    "StoppingCondition": {
        "MaxRuntimeInSeconds": 86400
    },
    "TrainingJobName": "mwaa-sm-training-job-61e653e50ae5461bb57c992f4a2ccff5"
}
[2021-11-17 23:20:05,065] {base_aws.py:401} INFO - Airflow Connection: aws_conn_id=aws_default
[2021-11-17 23:20:05,069] {base_aws.py:177} INFO - Credentials retrieved from login
[2021-11-17 23:20:05,070] {base_aws.py:88} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2021-11-17 23:20:05,070] {base_aws.py:90} INFO - Creating session with aws_access_key_id=AKIA4KH2UWGWPERNDCH5 region_name=us-west-2
[2021-11-17 23:20:05,085] {base_aws.py:168} INFO - role_arn is None
[2021-11-17 23:20:05,092] {logging_mixin.py:109} WARNING - /Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py:494 DeprecationWarning: client_type is deprecated. Set client_type from class attribute.
[2021-11-17 23:20:05,357] {sagemaker_training.py:101} INFO - Creating SageMaker training job mwaa-sm-training-job-61e653e50ae5461bb57c992f4a2ccff5.
[2021-11-17 23:20:05,359] {base_aws.py:401} INFO - Airflow Connection: aws_conn_id=aws_default
[2021-11-17 23:20:05,364] {base_aws.py:177} INFO - Credentials retrieved from login
[2021-11-17 23:20:05,365] {base_aws.py:88} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2021-11-17 23:20:05,366] {base_aws.py:90} INFO - Creating session with aws_access_key_id=AKIA4KH2UWGWPERNDCH5 region_name=us-west-2
[2021-11-17 23:20:05,379] {base_aws.py:168} INFO - role_arn is None
[2021-11-17 23:20:06,220] {sagemaker.py:790} INFO - 2021-11-18 07:20:06 Starting - Starting the training job
[2021-11-17 23:21:06,224] {base_aws.py:401} INFO - Airflow Connection: aws_conn_id=aws_default
[2021-11-17 23:21:06,232] {base_aws.py:177} INFO - Credentials retrieved from login
[2021-11-17 23:21:06,233] {base_aws.py:88} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2021-11-17 23:21:06,234] {base_aws.py:90} INFO - Creating session with aws_access_key_id=AKIA4KH2UWGWPERNDCH5 region_name=us-west-2
[2021-11-17 23:21:06,251] {base_aws.py:168} INFO - role_arn is None
[2021-11-17 23:21:06,744] {sagemaker.py:626} INFO - 2021-11-18 07:20:09 Starting - Launching requested ML instances
[2021-11-17 23:22:07,230] {sagemaker.py:626} INFO - 2021-11-18 07:21:15 Starting - Preparing the instances for training
[2021-11-17 23:23:07,792] {sagemaker.py:626} INFO - 2021-11-18 07:22:59 Downloading - Downloading input data
2021-11-18 07:22:59 Training - Downloading the training image
[2021-11-17 23:24:08,268] {sagemaker.py:609} INFO - Arguments: train
[2021-11-17 23:24:08,270] {sagemaker.py:609} INFO - [2021-11-18:07:23:16:INFO] Running standalone xgboost training.
[2021-11-17 23:24:08,271] {sagemaker.py:609} INFO - [2021-11-18:07:23:16:INFO] File size need to be processed in the node: 0.47mb. Available memory size in the node: 54719.97mb
[2021-11-17 23:24:08,272] {sagemaker.py:609} INFO - [2021-11-18:07:23:16:INFO] Determined delimiter of CSV input is ','
[2021-11-17 23:24:08,273] {sagemaker.py:609} INFO - [07:23:16] S3DistributionType set as FullyReplicated
[2021-11-17 23:24:08,273] {sagemaker.py:609} INFO - [07:23:16] 2130x69 matrix with 146970 entries loaded from /opt/ml/input/data/train?format=csv&label_column=0&delimiter=,
[2021-11-17 23:24:08,274] {sagemaker.py:609} INFO - [2021-11-18:07:23:16:INFO] Determined delimiter of CSV input is ','
[2021-11-17 23:24:08,274] {sagemaker.py:609} INFO - [07:23:16] S3DistributionType set as FullyReplicated
[2021-11-17 23:24:08,274] {sagemaker.py:609} INFO - [07:23:16] 869x69 matrix with 59961 entries loaded from /opt/ml/input/data/validation?format=csv&label_column=0&delimiter=,
[2021-11-17 23:24:08,275] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,275] {sagemaker.py:609} INFO - [0]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,276] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,276] {sagemaker.py:609} INFO - [1]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,277] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,277] {sagemaker.py:609} INFO - [2]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,277] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,278] {sagemaker.py:609} INFO - [3]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,278] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,279] {sagemaker.py:609} INFO - [4]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,279] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,280] {sagemaker.py:609} INFO - [5]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,280] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,280] {sagemaker.py:609} INFO - [6]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,281] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,281] {sagemaker.py:609} INFO - [7]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,282] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,282] {sagemaker.py:609} INFO - [8]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,283] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,283] {sagemaker.py:609} INFO - [9]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,284] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,284] {sagemaker.py:609} INFO - [10]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,285] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,285] {sagemaker.py:609} INFO - [11]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,286] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,287] {sagemaker.py:609} INFO - [12]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,287] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,287] {sagemaker.py:609} INFO - [13]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,288] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,288] {sagemaker.py:609} INFO - [14]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,289] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,289] {sagemaker.py:609} INFO - [15]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,289] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,290] {sagemaker.py:609} INFO - [16]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,290] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,291] {sagemaker.py:609} INFO - [17]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,291] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,291] {sagemaker.py:609} INFO - [18]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,292] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,292] {sagemaker.py:609} INFO - [19]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,292] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,293] {sagemaker.py:609} INFO - [20]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,293] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,294] {sagemaker.py:609} INFO - [21]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,294] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,294] {sagemaker.py:609} INFO - [22]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,295] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,295] {sagemaker.py:609} INFO - [23]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,295] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,296] {sagemaker.py:609} INFO - [24]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,296] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,296] {sagemaker.py:609} INFO - [25]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,297] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,297] {sagemaker.py:609} INFO - [26]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,298] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,298] {sagemaker.py:609} INFO - [27]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,298] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,299] {sagemaker.py:609} INFO - [28]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,299] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,300] {sagemaker.py:609} INFO - [29]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,300] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,301] {sagemaker.py:609} INFO - [30]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,301] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,302] {sagemaker.py:609} INFO - [31]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,303] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,304] {sagemaker.py:609} INFO - [32]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,305] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,305] {sagemaker.py:609} INFO - [33]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,305] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,306] {sagemaker.py:609} INFO - [34]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,306] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,307] {sagemaker.py:609} INFO - [35]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,307] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,307] {sagemaker.py:609} INFO - [36]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,308] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,308] {sagemaker.py:609} INFO - [37]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,308] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,309] {sagemaker.py:609} INFO - [38]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,309] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,310] {sagemaker.py:609} INFO - [39]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,310] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,310] {sagemaker.py:609} INFO - [40]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,311] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,311] {sagemaker.py:609} INFO - [41]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,311] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,312] {sagemaker.py:609} INFO - [42]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,312] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,312] {sagemaker.py:609} INFO - [43]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,313] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,313] {sagemaker.py:609} INFO - [44]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,313] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,314] {sagemaker.py:609} INFO - [45]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,314] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,314] {sagemaker.py:609} INFO - [46]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,315] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,315] {sagemaker.py:609} INFO - [47]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,315] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,316] {sagemaker.py:609} INFO - [48]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,316] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,316] {sagemaker.py:609} INFO - [49]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,317] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,317] {sagemaker.py:609} INFO - [50]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,318] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,318] {sagemaker.py:609} INFO - [51]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,319] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,319] {sagemaker.py:609} INFO - [52]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,319] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,320] {sagemaker.py:609} INFO - [53]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,320] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,321] {sagemaker.py:609} INFO - [54]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,321] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,321] {sagemaker.py:609} INFO - [55]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,322] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,322] {sagemaker.py:609} INFO - [56]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,322] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,323] {sagemaker.py:609} INFO - [57]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,323] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,323] {sagemaker.py:609} INFO - [58]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,324] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,324] {sagemaker.py:609} INFO - [59]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,324] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,325] {sagemaker.py:609} INFO - [60]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,325] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,325] {sagemaker.py:609} INFO - [61]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,326] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,326] {sagemaker.py:609} INFO - [62]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,326] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,327] {sagemaker.py:609} INFO - [63]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,327] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,327] {sagemaker.py:609} INFO - [64]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,328] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,328] {sagemaker.py:609} INFO - [65]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,328] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,328] {sagemaker.py:609} INFO - [66]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,329] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,329] {sagemaker.py:609} INFO - [67]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,330] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,330] {sagemaker.py:609} INFO - [68]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,330] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,331] {sagemaker.py:609} INFO - [69]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,331] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,331] {sagemaker.py:609} INFO - [70]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,331] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,332] {sagemaker.py:609} INFO - [71]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,332] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,332] {sagemaker.py:609} INFO - [72]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,333] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,333] {sagemaker.py:609} INFO - [73]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,334] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,334] {sagemaker.py:609} INFO - [74]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,334] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,335] {sagemaker.py:609} INFO - [75]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,336] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,337] {sagemaker.py:609} INFO - [76]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,337] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,338] {sagemaker.py:609} INFO - [77]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,338] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,338] {sagemaker.py:609} INFO - [78]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,339] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,339] {sagemaker.py:609} INFO - [79]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,339] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,340] {sagemaker.py:609} INFO - [80]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,340] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,340] {sagemaker.py:609} INFO - [81]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,341] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,341] {sagemaker.py:609} INFO - [82]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,341] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,341] {sagemaker.py:609} INFO - [83]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,342] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,342] {sagemaker.py:609} INFO - [84]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,342] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,343] {sagemaker.py:609} INFO - [85]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,343] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,343] {sagemaker.py:609} INFO - [86]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,344] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,344] {sagemaker.py:609} INFO - [87]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,344] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,345] {sagemaker.py:609} INFO - [88]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,345] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,345] {sagemaker.py:609} INFO - [89]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,346] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,346] {sagemaker.py:609} INFO - [90]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,346] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,347] {sagemaker.py:609} INFO - [91]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,347] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,347] {sagemaker.py:609} INFO - [92]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,348] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,348] {sagemaker.py:609} INFO - [93]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,348] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,348] {sagemaker.py:609} INFO - [94]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,349] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,349] {sagemaker.py:609} INFO - [95]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,350] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,350] {sagemaker.py:609} INFO - [96]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,350] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,351] {sagemaker.py:609} INFO - [97]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,351] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,352] {sagemaker.py:609} INFO - [98]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,352] {sagemaker.py:609} INFO - [07:23:16] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[2021-11-17 23:24:08,352] {sagemaker.py:609} INFO - [99]#011train-error:0#011validation-error:0
[2021-11-17 23:24:08,723] {sagemaker.py:626} INFO - 2021-11-18 07:23:58 Uploading - Uploading generated training model
2021-11-18 07:23:58 Completed - Training job completed
[2021-11-17 23:25:09,127] {sagemaker.py:852} INFO - Billable seconds: 81
[2021-11-17 23:25:09,362] {xcom.py:333} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-11-17 23:25:09,364] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1517, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2256, in xcom_push
    XCom.set(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/xcom.py", line 100, in set
    value = XCom.serialize_value(value)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/xcom.py", line 331, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
[2021-11-17 23:25:09,390] {taskinstance.py:1270} INFO - Marking task as FAILED. dag_id=mwaa-sm-customer-churn-dag, task_id=train, execution_date=20211118T071846, start_date=20211118T072004, end_date=20211118T072509
[2021-11-17 23:25:09,407] {standard_task_runner.py:88} ERROR - Failed to execute job 35 for task train
Traceback (most recent call last):
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1517, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2256, in xcom_push
    XCom.set(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/xcom.py", line 100, in set
    value = XCom.serialize_value(value)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/xcom.py", line 331, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
[2021-11-17 23:25:09,438] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-11-17 23:25:09,473] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
